CREATE TABLE users (
     USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     EMAIL VARCHAR(255) NOT NULL unique,
     PASSWORD VARCHAR(255) NOT NULL,
     ROLE VARCHAR(255) NOT NULL,
     ENABLED INT DEFAULT NULL
);

CREATE TABLE note(
     ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     title VARCHAR (255),
     content VARCHAR (2048),
     access VARCHAR (2048) CHECK (access IN ('private', 'public')),
     USER_ID INT  NOT NULL,
     FOREIGN KEY (USER_ID) REFERENCES users (USER_ID) ON DELETE CASCADE
);