CREATE TABLE users (
     USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     EMAIL VARCHAR(255) NOT NULL unique,
     PASSWORD VARCHAR(255) NOT NULL,
     ROLE VARCHAR(255) NOT NULL,
     ENABLED INT DEFAULT NULL
);

CREATE TABLE note(
     ID BIGINT PRIMARY KEY,
     title VARCHAR (100),
     content VARCHAR (10000),
     access VARCHAR (10),
     USER_ID INT  NOT NULL,
     FOREIGN KEY (USER_ID) REFERENCES users (USER_ID) ON DELETE CASCADE
);