INSERT INTO USERS (EMAIL, PASSWORD, ROLE, ENABLED)
VALUES ('syrovatkaaroslav@gmail.com',
        '{bcrypt}$2a$04$hRkj6yZS.DpUMKShtf93nedoiZhGHvKACwJ8AswlyHQ9ePV8DziwG',
'ROLE_USER', 1);

INSERT INTO USERS (EMAIL, PASSWORD, ROLE, ENABLED)
VALUES ('hameleoncheg@gmail.com',
'{bcrypt}$2a$04$mVKjSMt6LHzo/v5sPbdxIuuXpU9NoBRXNeYmfyaA1JIT9E7TTiIdO',
'ROLE_ADMIN', 1);

INSERT INTO USERS (EMAIL, PASSWORD, ROLE, ENABLED)
VALUES ('admin',
'{bcrypt}$2a$10$c7LCuviOwHXB1X0y9882wuIHnN/E9KBFJFZH0apVnvm9/zQbtgJJi',
'ROLE_ADMIN', 1);